version: '3.7'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.4
    ports:
      - '8443:8443'
    volumes:
      - ./keycloak:/keycloak
      - ./keycloak/test-realm.json:/opt/keycloak/data/import/test-realm.json
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTPS_CERTIFICATE_FILE: /keycloak/server.crt.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /keycloak/server.key.pem
      KC_HEALTH_ENABLED: true
    depends_on:
      - generate_cert
    command: ['start-dev', '--import-realm']

  generate_cert:
    container_name: generate_cert
    image: alpine/openssl
    volumes:
      - ./keycloak:/keycloak
    working_dir: /keycloak
    entrypoint: /bin/sh
    command: -c "openssl req --verbose -newkey rsa:2048 -nodes -keyout server.key.pem -x509 -days 3650 -out server.crt.pem -subj \"/C=US/ST=State/L=City/O=Organization/OU=Unit/CN=commonname/emailAddress=email@example.com\" && chmod 644 *.pem"
