version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: keycloak-postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    networks:
      - keycloak_network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTPS_CERTIFICATE_FILE: /keycloak/server.crt.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /keycloak/server.key.pem
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak-postgres
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: password
    ports:
      - 8443:8443
    volumes:
      - .:/keycloak
      - ./test-realm.json:/opt/keycloak/data/import/test-realm.json
    command: ['start-dev', '--import-realm']
    depends_on:
      - postgres
    networks:
      - keycloak_network

  generate_cert:
    container_name: generate_cert
    image: alpine/openssl
    volumes:
      - ./keycloak:/keycloak
    working_dir: /keycloak
    entrypoint: /bin/sh
    command: -c "openssl req --verbose -newkey rsa:2048 -nodes -keyout server.key.pem -x509 -days 3650 -out server.crt.pem -subj \"/C=US/ST=State/L=City/O=Organization/OU=Unit/CN=commonname/emailAddress=email@example.com\" && chmod 644 *.pem"

networks:
  keycloak_network:
    driver: bridge
